name: Docker Image Build

on:
  
  push:
    branches: [ main ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/samiam236/refi-web:${{ steps.get-latest-tag.outputs.tag }} --tag docker.io/samiam236/refi-web:latest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the Docker image
      run: docker push --all-tags docker.io/samiam236/refi-web
