name: Docker Image Build

on:

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/samiam236/refi-web:$(date +%s) --tag docker.io/samiam236/refi-web:latest
